### ISSUE TITLE
A bug when using the PeriodicSensor

### ISSUE THREAD

**Issue by mcgafm** [usnistgov/simprocesd#1]
Greetings!
I am tring to use the simprocesd package to simulate a process. A bug appear when using the PeriodicSensor Module. The Error says:"'PeriodicSensor' object has no attribute '_probes'". It seems that the Error appears during the initializing the PeriodicSensor because of the absence of the _probes attribute. The same Error was thrown when running the DataExploration.py sample.

**Comment by serghei-d** [comment]
Hello @mcgafm,
Thank you for the report but I am not able to reproduce the issue on the current master branch. Have you made any changes to the repo?
If the issue occurs without local changes, then please provide more information:
- How are you running the example? (such as the terminal commands used)
- The error stack when running example DataExploration.py
- Python version you are using to run the example.
